--- 
- name: Get an OpenStack instance
  hosts: localhost
  vars_files:
    - vault.yml
    - vars.yml
  
  tasks:
    - name: delete instance
      waldur_marketplace_os_instance:
        access_token: "{{ etais_access_token }}"
        api_url: "{{ api_url }}"
        project: "{{ project_name }}"
        name: "{{ instance_name }}"
        state: absent
    
