---
- name: restart bind
  service:
    name: named
    state: restarted
    enabled: yes
    masked: no

- name: reboot
  reboot:
    reboot_timeout: 3600

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
