--- 
- name: add 5005 to firewalld 
  firewalld:
    permanent: yes
    state: enabled
    port: "5005/tcp"
  notify: restart firewalld

- name: Add CNAME for container-proxy
  blockinfile:
    path: /etc/named/{{ hostname }}.{{ domain_name }}
    block: |
      container-proxy IN CNAME {{ hostname}}
    marker: 
      "; {mark} ANSIBLE MANAGED BLOCK for CNAME for container-proxy"
  notify: 
  - increase serial
  - restart bind

- name: create folder for container
  file: 
    path: /home/centos/docker_lab
    state: directory
    mode: 0755
    owner: root
    group: root

- name: copy server.py and Dockerfile to the docker_lab folder
  copy: 
    src: "{{ item }}"
    dest: /home/centos/docker_lab/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
  - server.py
  - Dockerfile

- name: docker build
  docker_image:
    name: docker_lab
    build:
      path: /home/centos/docker_lab
      pull: no
    source: build 

- name: create docker network 
  docker_network:
    name: docker_lab
    ipam_config:
    - subnet: "{{ docker.network.subnet }}"
      iprange: "{{ docker.network.iprange }}"
      gateway: "{{ docker.network.gateway }}"
    driver: bridge

- name: create whoami container 
  docker_container:
    name: whoami
    image: registry.hpc.ut.ee/mirror/containous/whoami
    pull: yes 
    restart_policy: always

- name: docker run 
  docker_container:
    name: docker_lab
    image: docker_lab
    hostname: docker-lab
    pull: no
    networks_cli_compatible: yes
    restart_policy: always
    networks:
    - name: docker_lab
      ipv4_address: "{{ docker.container_ip }}"
    exposed_ports:
      - '5000'
    ports: 
      - '5005:5000'

- name: create virtual host for container-proxy 
  template:
    src: virtualhostproxy.j2
    dest: /etc/httpd/conf.d/container-proxy.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart httpd




